[options]
; Configuración base para el proceso rápido de migración
admin_passwd = upgradernc_master_password
db_host = host.docker.internal
db_port = 5432
db_user = odoo
db_password = odoo
; Los addons incluyen el código nativo y el framework de OpenUpgrade
addons_path = /opt/odoo/addons,/opt/openupgrade
data_dir = /var/lib/odoo
list_db = True
proxy_mode = True
workers = 0
